[alembic]
# path to migration scripts
script_location = alembic

# template for migration file names
file_template = %%(rev)s_%%(slug)s

# timezone for timestamps within revision files
# leave blank for UTC
timezone =

# max length of characters to truncate from version names
# truncate_slug_length = 40

# set to 'true' to capture database schema version from
# alembic_version table representing current database state.
# Requires that the database schema has been initialized with
# the alembic_version table.
# Useful for startups and init scenarios.
# version_table_schema =

# set to true to search for versions across multiple branches
# branch_independent = false

# specify a subdirectory in script_location that should be used
# for new revisions
# version_locations = %(here)s/versions

# the file encoding used to create new migration scripts
# revision_environment = false

# if true, will include the date in new migration file names
# new_revision_date_in_file = false

# if true, will output the full path to new migration files
# output_full_path = false

# SQLAlchemy database URL
sqlalchemy.url = postgresql://user:password@host:port/dbname  # Will be replaced by env var in env.py

[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# on newly generated revision scripts.  See documentation for
# details.

# format using "black" - use "black --version" to see
# what version of black is installed locally
# black =
#    type = exec
#    entrypoint = black
#    options = -l 88 %(path)s

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %%(levelname)-5.5s [%%(name)s] %%(message)s
datefmt = %%H:%%M:%%S
